Second task solution
js-tasks-ru/jsbasic-20210225_gyuzeliya-muhamadieva pull request #2
Opened 2021-03-01 22:16 UTC by Gyuzeliya

2021-03-01 22:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-02 11:36 UTC, SinimaWath requested changes

2021-03-02 11:36 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  let count = 1;
Название переменной не говорящее, другой разработчик не поймет, зачем она нужна:
переменная должна говорить:
- Что она хранит
- Для чего хранит

`count` - обозначают обычно как количество или счетчик. В твоем случае это явно не так

2021-03-02 11:36 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return name && name.length > 3 && name.search(/\s/) === -1 || false;
Можно обойтись без регулярки и лучше нужно. Почему:
- Регулярки всегда сложнее поддерживать
- Регулярки сложно читать.

Переделай на includes, более понятный и подходящий метод

2021-03-02 11:36 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  const targets = ['1XbeT', 'xxxxx'];
- Это хороший пример переменных конфига. Нужно вынести в глобальную область, чтобы не создавать массив на каждый вызов функции: `const SPAM_TARGETS = ['1XbeT', 'xxxxx']`;

2021-03-02 11:36 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  for (let target of targets) {
target - у тебя неизменяемая переменная и лучше ее переделать на const

`for (const target of SPAM_TARGETS)`

2021-03-02 11:36 UTC, SinimaWath commented on 1-module/4-task/index.js
> +    if (str.toLowerCase().includes(target.toLowerCase())) {
Оптимальней будет заранее до цикла посчитать str.toLowerCase(), чтобы на каждую итерацию этого не делать

2021-03-04 12:01 UTC, closed without merging